language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

addons:
  sonarcloud:
    organization: "blazinghorizon"
    token:
      secure: "360a8d75b6bdc114a1e87626388aad48b7323bb5"

cache:
  directories:
  - '$HOME/.sonar/cache'

notifications:
  email: false
