language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

addons:
  sonarcloud:
    organization: "blazinghorizon"
    token:
      secure: "edf88bf708d58dde7fb9fd279a08cd5f5d0a9796"

notifications:
  email: false
